//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomIDCard.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandomIDCard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;areas&gt;
        ///	&lt;area code=&quot;110000&quot; name=&quot;北京市&quot; /&gt;
        ///	&lt;area code=&quot;110100&quot; name=&quot;市辖区&quot; /&gt;
        ///	&lt;area code=&quot;110101&quot; name=&quot;东城区&quot; /&gt;
        ///	&lt;area code=&quot;110102&quot; name=&quot;西城区&quot; /&gt;
        ///	&lt;area code=&quot;110103&quot; name=&quot;崇文区&quot; /&gt;
        ///	&lt;area code=&quot;110104&quot; name=&quot;宣武区&quot; /&gt;
        ///	&lt;area code=&quot;110105&quot; name=&quot;朝阳区&quot; /&gt;
        ///	&lt;area code=&quot;110106&quot; name=&quot;丰台区&quot; /&gt;
        ///	&lt;area code=&quot;110107&quot; name=&quot;石景山区&quot; /&gt;
        ///	&lt;area code=&quot;110108&quot; name=&quot;海淀区&quot; /&gt;
        ///	&lt;area code=&quot;110109&quot; name=&quot;门头沟区&quot; /&gt;
        ///	&lt;area code=&quot;110111&quot; name=&quot;房山区&quot; /&gt;
        ///	&lt;area code=&quot;110112&quot; name=&quot;通州区&quot; /&gt;
        ///	&lt;area  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AreaCodeInfo {
            get {
                return ResourceManager.GetString("AreaCodeInfo", resourceCulture);
            }
        }
    }
}
